export const intakeClientJs = [
  "document.querySelectorAll('[data-intake-root]').forEach((root) => {",
  "  const form = root.querySelector('[data-intake-form]');",
  "  if (!form) return;",
  "  const steps = Array.from(root.querySelectorAll('[data-intake-step-panel]'));",
  "  const prev = root.querySelector('[data-intake-prev]');",
  "  const next = root.querySelector('[data-intake-next]');",
  "  const submit = root.querySelector('[data-intake-submit]');",
  "  const progress = root.querySelector('[data-intake-progress]');",
  "  const progressTemplate = progress?.dataset.intakeProgressTemplate || '';",
  "  const resultInput = root.querySelector('[data-intake-result-key]');",
  "  const results = Array.from(root.querySelectorAll('[data-intake-result]'));",
  "  const resultsWrap = root.querySelector('[data-intake-results]');",
  "  let current = 0;",
  "  const fieldValue = (name) => {",
  "    const value = new FormData(form).get(name);",
  "    return value == null ? '' : String(value);",
  "  };",
  "  const matches = (el) => {",
  "    const field = el.dataset.intakeWhenField || '';",
  "    if (!field) return true;",
  "    const values = (el.dataset.intakeWhenValue || '').split('|').filter(Boolean);",
  "    return values.includes(fieldValue(field));",
  "  };",
  "  const sync = () => {",
  "    root.querySelectorAll('[data-intake-field]').forEach((field) => {",
  "      const visible = matches(field);",
  "      field.hidden = !visible;",
  "      field.querySelectorAll('input, select, textarea').forEach((control) => {",
  "        control.disabled = !visible;",
  "        if (!visible) {",
  "          if (control.type === 'checkbox' || control.type === 'radio') control.checked = false;",
  "          else control.value = '';",
  "        }",
  "      });",
  "    });",
  "    current = Math.max(0, Math.min(current, steps.length - 1));",
  "    steps.forEach((step, index) => { step.hidden = index !== current; });",
  "    const selectedResult = results.find(matches) || results[0];",
  "    if (resultInput && selectedResult) resultInput.value = selectedResult.dataset.intakeResult || '';",
  "    if (progress) progress.textContent = progressTemplate.replace('{current}', String(current + 1)).replace('{total}', String(steps.length));",
  "    if (prev) prev.hidden = current === 0;",
  "    if (next) next.hidden = current >= steps.length - 1;",
  "    if (submit) submit.hidden = current < steps.length - 1;",
  "  };",
  "  form.addEventListener('input', sync);",
  "  form.addEventListener('change', sync);",
  "  prev?.addEventListener('click', () => { current -= 1; sync(); });",
  "  next?.addEventListener('click', () => { current += 1; sync(); });",
  "  form.addEventListener('mantle:form-success', () => {",
  "    const selected = resultInput?.value || '';",
  "    if (resultsWrap) resultsWrap.hidden = false;",
  "    results.forEach((result) => {",
  "      result.hidden = result.dataset.intakeResult !== selected;",
  "    });",
  "  });",
  "  sync();",
  "});",
];
