// Generated by scripts/build-styles.mjs. Do not edit.
export const assetBuild = "2c777f3c5adcab46";

export function asset(path: string): string {
  return path.startsWith("/") ? `${path}?v=${assetBuild}` : path;
}
