// Generated by scripts/build-styles.mjs. Do not edit.
export const assetBuild = "053f6a96bfdbef86";

export function asset(path: string): string {
  return path.startsWith("/") ? `${path}?v=${assetBuild}` : path;
}
