// Generated by scripts/build-styles.mjs. Do not edit.
export const assetBuild = "68ff8b3fdf4a34a1";

export function asset(path: string): string {
  return path.startsWith("/") ? `${path}?v=${assetBuild}` : path;
}
