export const formClientJs = [
  "document.querySelectorAll('[data-mantle-form]').forEach((form) => {",
  "  form.addEventListener('submit', async (event) => {",
  "    event.preventDefault();",
  "    const isIntake = form.dataset.intakeForm === 'true';",
  "    const status = form.querySelector('[data-mantle-form-status]');",
  "    const button = form.querySelector('button[type=\"submit\"]');",
  "    const turnstile = form.querySelector('.cf-turnstile');",
  "    const setStatus = (message, error) => {",
  "      if (!status) return;",
  "      status.hidden = false;",
  "      status.textContent = message;",
  "      if (error) status.dataset.error = 'true';",
  "      else delete status.dataset.error;",
  "    };",
  "    if (button) button.disabled = true;",
  "    setStatus(form.dataset.mantlePendingMessage || '', false);",
  "    try {",
  "      const body = Object.fromEntries(Array.from(new FormData(form).entries(), ([name, value]) => {",
  "        const control = form.elements.namedItem(name);",
  "        return [name, control?.type === 'number' && value !== '' ? Number(value) : value];",
  "      }));",
  "      const res = await fetch(form.action, {",
  "        method: form.method || 'POST',",
  "        headers: { 'content-type': 'application/json' },",
  "        body: JSON.stringify(body),",
  "      });",
  "      const payload = await res.json().catch(() => null);",
  "      if (!res.ok || payload?.ok === false) {",
  "        throw new Error(payload?.diagnostic?.message || form.dataset.mantleErrorMessage || '');",
  "      }",
  "      form.dispatchEvent(new CustomEvent('mantle:form-success', { detail: { payload } }));",
  "      if (!isIntake) form.reset();",
  "      setStatus(form.dataset.mantleSuccessMessage || '', false);",
  "    } catch (error) {",
  "      setStatus(error instanceof Error ? error.message : form.dataset.mantleErrorMessage || '', true);",
  "    } finally {",
  "      if (turnstile && window.turnstile?.reset) window.turnstile.reset(turnstile);",
  "      if (button) button.disabled = false;",
  "    }",
  "  });",
  "});",
];
