export const navClientJs = [
  "const updateSiteNav = () => {",
  "  document.querySelectorAll('[data-site-nav]').forEach((nav) => {",
  "    nav.dataset.scrolled = window.scrollY > 8 ? 'true' : 'false';",
  "  });",
  "};",
  "updateSiteNav();",
  "window.addEventListener('scroll', updateSiteNav, { passive: true });",
  "document.querySelectorAll('[data-mobile-nav]').forEach((sheet) => {",
  "  const root = sheet.closest('nav');",
  "  const trigger = root?.querySelector('[data-mobile-nav-trigger]');",
  "  const panel = sheet.querySelector('[data-sheet-content]');",
  "  if (!trigger) return;",
  "  const setOpen = (open) => {",
  "    sheet.dataset.state = open ? 'open' : 'closed';",
  "    trigger.setAttribute('aria-expanded', open ? 'true' : 'false');",
  "    document.body.style.overflow = open ? 'hidden' : '';",
  "    if (open) panel?.querySelector('a, button')?.focus();",
  "  };",
  "  trigger.addEventListener('click', () => setOpen(sheet.dataset.state !== 'open'));",
  "  sheet.querySelectorAll('[data-mobile-nav-close]').forEach((el) => {",
  "    el.addEventListener('click', () => setOpen(false));",
  "  });",
  "  document.addEventListener('keydown', (event) => {",
  "    if (event.key === 'Escape' && sheet.dataset.state === 'open') setOpen(false);",
  "  });",
  "});",
];
