export const themeClientJs = [
  "const THEME_KEY = 'mantle-theme';",
  "const readTheme = () => {",
  "  const stored = localStorage.getItem(THEME_KEY);",
  "  if (stored === 'light' || stored === 'dark') return stored;",
  "  return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';",
  "};",
  "const applyTheme = (theme) => {",
  "  document.documentElement.classList.toggle('dark', theme === 'dark');",
  "  document.querySelectorAll('img[src*=\"/assets/mantle-ocean-hero-light.svg\"], img[src*=\"/assets/mantle-ocean-hero-dark.svg\"]').forEach((image) => {",
  "    const src = image.getAttribute('src') || '';",
  "    const nextSrc = theme === 'dark' ? src.replace('/assets/mantle-ocean-hero-light.svg', '/assets/mantle-ocean-hero-dark.svg') : src.replace('/assets/mantle-ocean-hero-dark.svg', '/assets/mantle-ocean-hero-light.svg');",
  "    if (nextSrc && image.getAttribute('src') !== nextSrc) image.setAttribute('src', nextSrc);",
  "  });",
  "  document.querySelectorAll('[data-theme-toggle]').forEach((button) => {",
  "    button.dataset.theme = theme;",
  "    button.setAttribute('aria-pressed', theme === 'dark' ? 'true' : 'false');",
  "    button.querySelectorAll('[data-theme-label]').forEach((label) => {",
  "      label.textContent = theme === 'dark' ? button.dataset.lightModeLabel || '' : button.dataset.darkModeLabel || '';",
  "    });",
  "  });",
  "};",
  "applyTheme(readTheme());",
  "window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', () => {",
  "  if (!localStorage.getItem(THEME_KEY)) applyTheme(readTheme());",
  "});",
  "document.querySelectorAll('[data-theme-toggle]').forEach((button) => {",
  "  button.addEventListener('click', () => {",
  "    const next = document.documentElement.classList.contains('dark') ? 'light' : 'dark';",
  "    localStorage.setItem(THEME_KEY, next);",
  "    applyTheme(next);",
  "  });",
  "});",
];
